/**
 * Copyright (c) 2004 - 2008 Eike Stepper, Germany.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *    Eike Stepper - initial API and implementation
 *
 * $Id: PopItemProviderAdapterFactory.java,v 1.4 2008-08-09 09:26:22 estepper Exp $
 */
package org.eclipse.net4j.pop.provider;

import org.eclipse.net4j.internal.pop.bundle.Activator;
import org.eclipse.net4j.pop.PopPackage;
import org.eclipse.net4j.pop.util.PopAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ChildCreationExtenderManager;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemColorProvider;
import org.eclipse.emf.edit.provider.IItemFontProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITableItemColorProvider;
import org.eclipse.emf.edit.provider.ITableItemFontProvider;
import org.eclipse.emf.edit.provider.ITableItemLabelProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The adapters generated by this
 * factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The adapters
 * also support Eclipse property sheets. Note that most of the adapters are shared among multiple instances. <!--
 * begin-user-doc --> <!-- end-user-doc -->
 * 
 * @generated
 */
public class PopItemProviderAdapterFactory extends PopAdapterFactory implements ComposeableAdapterFactory,
    IChangeNotifier, IDisposable, IChildCreationExtender
{
  /**
   * This keeps track of the root adapter factory that delegates to this adapter factory.
   * <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * @generated
   */
  protected ComposedAdapterFactory parentAdapterFactory;

  /**
   * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
   * <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * @generated
   */
  protected IChangeNotifier changeNotifier = new ChangeNotifier();

  /**
   * This helps manage the child creation extenders.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  protected ChildCreationExtenderManager childCreationExtenderManager = new ChildCreationExtenderManager(
      Activator.INSTANCE, PopPackage.eNS_URI);

  /**
   * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected Collection<Object> supportedTypes = new ArrayList<Object>();

  /**
   * This constructs an instance.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  public PopItemProviderAdapterFactory()
  {
    supportedTypes.add(IEditingDomainItemProvider.class);
    supportedTypes.add(IStructuredItemContentProvider.class);
    supportedTypes.add(ITreeItemContentProvider.class);
    supportedTypes.add(IItemLabelProvider.class);
    supportedTypes.add(IItemPropertySource.class);
    supportedTypes.add(ITableItemLabelProvider.class);
    supportedTypes.add(ITableItemColorProvider.class);
    supportedTypes.add(ITableItemFontProvider.class);
    supportedTypes.add(IItemColorProvider.class);
    supportedTypes.add(IItemFontProvider.class);
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.PopManager} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PopManagerItemProvider popManagerItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.PopManager}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createPopManagerAdapter()
  {
    if (popManagerItemProvider == null)
    {
      popManagerItemProvider = new PopManagerItemProvider(this);
    }

    return popManagerItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Pop} instances.
   * <!-- begin-user-doc
   * --> <!-- end-user-doc -->
   * @generated
   */
  protected PopItemProvider popItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Pop}.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createPopAdapter()
  {
    if (popItemProvider == null)
    {
      popItemProvider = new PopItemProvider(this);
    }

    return popItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.PrimaryModule} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected PrimaryModuleItemProvider primaryModuleItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.PrimaryModule}.
   * <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createPrimaryModuleAdapter()
  {
    if (primaryModuleItemProvider == null)
    {
      primaryModuleItemProvider = new PrimaryModuleItemProvider(this);
    }

    return primaryModuleItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Repository} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected RepositoryItemProvider repositoryItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Repository}. <!-- begin-user-doc --> <!-- end-user-doc
   * -->
   * 
   * @generated
   */
  @Override
  public Adapter createRepositoryAdapter()
  {
    if (repositoryItemProvider == null)
    {
      repositoryItemProvider = new RepositoryItemProvider(this);
    }

    return repositoryItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Developer} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected DeveloperItemProvider developerItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Developer}. <!-- begin-user-doc --> <!-- end-user-doc
   * -->
   * 
   * @generated
   */
  @Override
  public Adapter createDeveloperAdapter()
  {
    if (developerItemProvider == null)
    {
      developerItemProvider = new DeveloperItemProvider(this);
    }

    return developerItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.TaskGroup} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected TaskGroupItemProvider taskGroupItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.TaskGroup}. <!-- begin-user-doc --> <!-- end-user-doc
   * -->
   * 
   * @generated
   */
  @Override
  public Adapter createTaskGroupAdapter()
  {
    if (taskGroupItemProvider == null)
    {
      taskGroupItemProvider = new TaskGroupItemProvider(this);
    }

    return taskGroupItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Task} instances.
   * <!-- begin-user-doc
   * --> <!-- end-user-doc -->
   * @generated
   */
  protected TaskItemProvider taskItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Task}.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createTaskAdapter()
  {
    if (taskItemProvider == null)
    {
      taskItemProvider = new TaskItemProvider(this);
    }

    return taskItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Tag} instances.
   * <!-- begin-user-doc
   * --> <!-- end-user-doc -->
   * @generated
   */
  protected TagItemProvider tagItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Tag}.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createTagAdapter()
  {
    if (tagItemProvider == null)
    {
      tagItemProvider = new TagItemProvider(this);
    }

    return tagItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.MainBranch} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected MainBranchItemProvider mainBranchItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.MainBranch}. <!-- begin-user-doc --> <!-- end-user-doc
   * -->
   * 
   * @generated
   */
  @Override
  public Adapter createMainBranchAdapter()
  {
    if (mainBranchItemProvider == null)
    {
      mainBranchItemProvider = new MainBranchItemProvider(this);
    }

    return mainBranchItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.SubBranch} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected SubBranchItemProvider subBranchItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.SubBranch}. <!-- begin-user-doc --> <!-- end-user-doc
   * -->
   * 
   * @generated
   */
  @Override
  public Adapter createSubBranchAdapter()
  {
    if (subBranchItemProvider == null)
    {
      subBranchItemProvider = new SubBranchItemProvider(this);
    }

    return subBranchItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.DeliveryStream} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected DeliveryStreamItemProvider deliveryStreamItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.DeliveryStream}.
   * <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDeliveryStreamAdapter()
  {
    if (deliveryStreamItemProvider == null)
    {
      deliveryStreamItemProvider = new DeliveryStreamItemProvider(this);
    }

    return deliveryStreamItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.DevelopmentStream} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DevelopmentStreamItemProvider developmentStreamItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.DevelopmentStream}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDevelopmentStreamAdapter()
  {
    if (developmentStreamItemProvider == null)
    {
      developmentStreamItemProvider = new DevelopmentStreamItemProvider(this);
    }

    return developmentStreamItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.MaintenanceStream} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected MaintenanceStreamItemProvider maintenanceStreamItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.MaintenanceStream}.
   * <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createMaintenanceStreamAdapter()
  {
    if (maintenanceStreamItemProvider == null)
    {
      maintenanceStreamItemProvider = new MaintenanceStreamItemProvider(this);
    }

    return maintenanceStreamItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Release} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected ReleaseItemProvider releaseItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Release}.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createReleaseAdapter()
  {
    if (releaseItemProvider == null)
    {
      releaseItemProvider = new ReleaseItemProvider(this);
    }

    return releaseItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Milestone} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected MilestoneItemProvider milestoneItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Milestone}. <!-- begin-user-doc --> <!-- end-user-doc
   * -->
   * 
   * @generated
   */
  @Override
  public Adapter createMilestoneAdapter()
  {
    if (milestoneItemProvider == null)
    {
      milestoneItemProvider = new MilestoneItemProvider(this);
    }

    return milestoneItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Delivery} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected DeliveryItemProvider deliveryItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Delivery}.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDeliveryAdapter()
  {
    if (deliveryItemProvider == null)
    {
      deliveryItemProvider = new DeliveryItemProvider(this);
    }

    return deliveryItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Integration} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected IntegrationItemProvider integrationItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Integration}. <!-- begin-user-doc --> <!-- end-user-doc
   * -->
   * 
   * @generated
   */
  @Override
  public Adapter createIntegrationAdapter()
  {
    if (integrationItemProvider == null)
    {
      integrationItemProvider = new IntegrationItemProvider(this);
    }

    return integrationItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.CheckoutManager} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected CheckoutManagerItemProvider checkoutManagerItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.CheckoutManager}.
   * <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createCheckoutManagerAdapter()
  {
    if (checkoutManagerItemProvider == null)
    {
      checkoutManagerItemProvider = new CheckoutManagerItemProvider(this);
    }

    return checkoutManagerItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Checkout} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected CheckoutItemProvider checkoutItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Checkout}.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createCheckoutAdapter()
  {
    if (checkoutItemProvider == null)
    {
      checkoutItemProvider = new CheckoutItemProvider(this);
    }

    return checkoutItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.WorkspaceSpecification} instances.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  protected WorkspaceSpecificationItemProvider workspaceSpecificationItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.WorkspaceSpecification}.
   * <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createWorkspaceSpecificationAdapter()
  {
    if (workspaceSpecificationItemProvider == null)
    {
      workspaceSpecificationItemProvider = new WorkspaceSpecificationItemProvider(this);
    }

    return workspaceSpecificationItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.SecondaryModule} instances. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @generated
   */
  protected SecondaryModuleItemProvider secondaryModuleItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.SecondaryModule}.
   * <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createSecondaryModuleAdapter()
  {
    if (secondaryModuleItemProvider == null)
    {
      secondaryModuleItemProvider = new SecondaryModuleItemProvider(this);
    }

    return secondaryModuleItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.eclipse.net4j.pop.Assignee} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AssigneeItemProvider assigneeItemProvider;

  /**
   * This creates an adapter for a {@link org.eclipse.net4j.pop.Assignee}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createAssigneeAdapter()
  {
    if (assigneeItemProvider == null)
    {
      assigneeItemProvider = new AssigneeItemProvider(this);
    }

    return assigneeItemProvider;
  }

  /**
   * This returns the root adapter factory that contains this factory.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  public ComposeableAdapterFactory getRootAdapterFactory()
  {
    return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
  }

  /**
   * This sets the composed adapter factory that contains this factory.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory)
  {
    this.parentAdapterFactory = parentAdapterFactory;
  }

  /**
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object type)
  {
    return supportedTypes.contains(type) || super.isFactoryForType(type);
  }

  /**
   * This implementation substitutes the factory itself as the key for the adapter.
   * <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * @generated
   */
  @Override
  public Adapter adapt(Notifier notifier, Object type)
  {
    return super.adapt(notifier, this);
  }

  /**
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object adapt(Object object, Object type)
  {
    if (isFactoryForType(type))
    {
      Object adapter = super.adapt(object, type);
      if (!(type instanceof Class) || (((Class<?>)type).isInstance(adapter)))
      {
        return adapter;
      }
    }

    return null;
  }

  /**
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  public List<IChildCreationExtender> getChildCreationExtenders()
  {
    return childCreationExtenderManager.getChildCreationExtenders();
  }

  /**
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  public Collection<?> getNewChildDescriptors(Object object, EditingDomain editingDomain)
  {
    return childCreationExtenderManager.getNewChildDescriptors(object, editingDomain);
  }

  /**
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  public ResourceLocator getResourceLocator()
  {
    return childCreationExtenderManager;
  }

  /**
   * This adds a listener.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  public void addListener(INotifyChangedListener notifyChangedListener)
  {
    changeNotifier.addListener(notifyChangedListener);
  }

  /**
   * This removes a listener.
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  public void removeListener(INotifyChangedListener notifyChangedListener)
  {
    changeNotifier.removeListener(notifyChangedListener);
  }

  /**
   * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
   * <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * @generated
   */
  public void fireNotifyChanged(Notification notification)
  {
    changeNotifier.fireNotifyChanged(notification);

    if (parentAdapterFactory != null)
    {
      parentAdapterFactory.fireNotifyChanged(notification);
    }
  }

  /**
   * This disposes all of the item providers created by this factory. 
   * <!-- begin-user-doc --> <!-- end-user-doc -->
   * @generated
   */
  public void dispose()
  {
    if (popManagerItemProvider != null)
      popManagerItemProvider.dispose();
    if (popItemProvider != null)
      popItemProvider.dispose();
    if (primaryModuleItemProvider != null)
      primaryModuleItemProvider.dispose();
    if (repositoryItemProvider != null)
      repositoryItemProvider.dispose();
    if (developerItemProvider != null)
      developerItemProvider.dispose();
    if (taskGroupItemProvider != null)
      taskGroupItemProvider.dispose();
    if (taskItemProvider != null)
      taskItemProvider.dispose();
    if (tagItemProvider != null)
      tagItemProvider.dispose();
    if (mainBranchItemProvider != null)
      mainBranchItemProvider.dispose();
    if (subBranchItemProvider != null)
      subBranchItemProvider.dispose();
    if (deliveryStreamItemProvider != null)
      deliveryStreamItemProvider.dispose();
    if (developmentStreamItemProvider != null)
      developmentStreamItemProvider.dispose();
    if (maintenanceStreamItemProvider != null)
      maintenanceStreamItemProvider.dispose();
    if (releaseItemProvider != null)
      releaseItemProvider.dispose();
    if (milestoneItemProvider != null)
      milestoneItemProvider.dispose();
    if (deliveryItemProvider != null)
      deliveryItemProvider.dispose();
    if (integrationItemProvider != null)
      integrationItemProvider.dispose();
    if (checkoutManagerItemProvider != null)
      checkoutManagerItemProvider.dispose();
    if (checkoutItemProvider != null)
      checkoutItemProvider.dispose();
    if (workspaceSpecificationItemProvider != null)
      workspaceSpecificationItemProvider.dispose();
    if (secondaryModuleItemProvider != null)
      secondaryModuleItemProvider.dispose();
    if (assigneeItemProvider != null)
      assigneeItemProvider.dispose();
  }

}
