<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pop"
    nsURI="http://pop/1.0" nsPrefix="pop">
  <eClassifiers xsi:type="ecore:EClass" name="Branch" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branchName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//Tag"
        containment="true" eOpposite="#//Tag/branch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="branch" lowerBound="1"
        eType="#//Branch" eOpposite="#//Branch/tags"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stream" abstract="true" eSuperTypes="#//Branch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="releases" upperBound="-1"
        eType="#//Release" containment="true" resolveProxies="false" eOpposite="#//Release/stream"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/stream"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="merges" upperBound="-1"
        eType="#//Merge" containment="true" eOpposite="#//Merge/stream"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Branch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stream" lowerBound="1"
        eType="#//Stream" eOpposite="#//Stream/tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliveries" upperBound="-1"
        eType="#//Delivery" containment="true" eOpposite="#//Delivery/task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delivery" eSuperTypes="#//Tag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="merges" upperBound="-1"
        eType="#//Merge" eOpposite="#//Merge/delivery"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1" eType="#//Task"
        eOpposite="#//Task/deliveries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Merge" eSuperTypes="#//Tag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delivery" lowerBound="1"
        eType="#//Delivery" eOpposite="#//Delivery/merges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stream" lowerBound="1"
        eType="#//Stream" eOpposite="#//Stream/merges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DevelopmentStream" abstract="true" eSuperTypes="#//Stream">
    <eStructuralFeatures xsi:type="ecore:EReference" name="maintenanceStreams" upperBound="-1"
        eType="#//MaintenanceStream" eOpposite="#//MaintenanceStream/developmentStream"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaintenanceStream" eSuperTypes="#//Stream">
    <eStructuralFeatures xsi:type="ecore:EReference" name="developmentStream" lowerBound="1"
        eType="#//DevelopmentStream" eOpposite="#//DevelopmentStream/maintenanceStreams"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//DevelopmentStream">
    <eStructuralFeatures xsi:type="ecore:EReference" name="committers" lowerBound="1"
        upperBound="-1" eType="#//Committer" containment="true" resolveProxies="false"
        eOpposite="#//Committer/project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeRoots" lowerBound="1"
        upperBound="-1" eType="#//CodeRoot" containment="true" resolveProxies="false"
        eOpposite="#//CodeRoot/project"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Release">
    <eStructuralFeatures xsi:type="ecore:EReference" name="milestones" upperBound="-1"
        eType="#//Milestone" containment="true" resolveProxies="false" eOpposite="#//Milestone/release"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stream" lowerBound="1"
        eType="#//Stream" eOpposite="#//Stream/releases"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Milestone">
    <eStructuralFeatures xsi:type="ecore:EReference" name="release" lowerBound="1"
        eType="#//Release" eOpposite="#//Release/milestones"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="milestoneName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Committer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/committers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/codeRoots"/>
  </eClassifiers>
</ecore:EPackage>
